name: tesi_magistrale
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11.8
  - pip
  - pip:
    - git+https://gitlab.com/ase/ase.git
    - mace-torch==0.3.4
    - torch-dftd==0.4.0
  - phonopy=2.21.2
  - seekpath=2.1.0
  - marimo=0.3.1
  - pandas=2.2.0
  - polars=0.20.13
