[tool.poetry]
name = "tesi-magistrale"
version = "0.1.0"
description = "Tesi magistrale di Mariano Mollo"
authors = ["Mariano Mollo <marian.mollo@studenti.unina.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ase = "^3.22.1"
jupyterlab = "^4.0.11"
pandas = "^2.2.0"
marimo = "^0.2.8"
polars = "^0.20.13"
hvplot = "^0.9.2"
pyarrow = "^15.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
