[tool.poetry]
package-mode = false
name = "tesi-magistrale"
version = "0.1.0"
description = "Tesi magistrale di Mariano Mollo, ambiente di sviluppo locale"
authors = ["Mariano Mollo <marian.mollo@studenti.unina.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ase = {git = "https://gitlab.com/ase/ase.git"}
marimo = "^0.2.8"
pandas = "^2.2.0"
polars = "^0.20.13"
hvplot = "^0.9.2"
pyarrow = "^15.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
