# Use runphon to calculate the forces
# Then use phon to get the phonon dispersions frequencies along the bandpath
chmod +x runphon
./runphon

# Turn off the supercell generation and execute phon
cat > INPHON <<EOF
# Generated by harmonic.sh

LSUPER = .F.

# number of ions types and masses
NTYPES = 2
MASS = 1.008 15.999

# q points section
LRECIP = .TRUE.
ND = 6
NPOINTS = 51

QI = \
    0.00000000     0.00000000     0.00000000 \
    0.00000000     0.00000000    -0.50000000 \
    0.33333333    -0.33333333     0.00000000 \
    0.33333333    -0.33333333    -0.50000000 \
    0.50000000     0.00000000     0.00000000 \
    0.50000000     0.00000000    -0.50000000

QF = \
    0.00000000     0.00000000    -0.50000000 \
    0.33333333    -0.33333333     0.00000000 \
    0.33333333    -0.33333333    -0.50000000 \
    0.50000000     0.00000000     0.00000000 \
    0.50000000     0.00000000    -0.50000000 \
    0.00000000     0.00000000     0.00000000
EOF

./phon
# This gives us a FREQ.cm file that we can plot against experiment
# Save frequencies for later
# mv FREQ.cm FREQ.cm.s$s.k$k
# mv FREQ FREQ.s$s.k$k

