[language-server.tinymist]
command = "tinymist"
config = { formatterMode = "typstyle" }

[[language]]
name = "typst"
language-servers = ["tinymist"]
# formatter = { command = "typstfmt", args = ["--output", "-"] }
# auto-format = true
